Feature/3 occurrence purging system
bitcaster-io/bitcaster pull request #9
Opened 2024-08-09 14:47 UTC by SimoMart88

2024-08-11 20:34 UTC, saxix requested changes

2024-08-11 20:34 UTC, saxix commented on tests/admin/test_admin_occurrence.py
> +
use `user_grant_permissions` here

2024-08-12 07:58 UTC, SimoMart88 commented on tests/admin/test_admin_occurrence.py
> +
:+1: done!

2024-08-27 16:33 UTC, saxix approved these changes

2024-08-27 16:34 UTC, hanarero approved these changes

2024-08-27 16:34 UTC, merged